### ISSUE TITLE
Thick border on top bar / weird Java application border

### ISSUE THREAD

**Issue by Bosma** [jnsh/arc-theme#211]
### Before submitting

- Ensure that the issue is present with the latest Arc-theme release, or latest git snapshot. **Yes.**
- Test whether the issue also appears with default themes (e.g. Adwaita for GTK and GNOME). **No.**
- Make sure you have built the correct theme versions for GTK 3, GNOME Shell and Cinnamon themes. **Yes.**
- Make sure the issue persists between restarts. **Yes.**
- For GTK 3 related issues, try clearing your user's `~/.config/gtk-3.0/gtk.css`, if it exists. **Doesn't exist.**

### Details

Please add the following information:

- Distribution and version. **Arch**
- Versions for the affected applications/desktops/toolkits. **gnome-shell 1:44.1-3** 
- Installation method (package or compiled manually). **arch package arc-gtk-theme**
- Arc-theme version. **arc-gtk-theme 20221218-1**

Unless this is a non-visual issue, always add screenshots to help describe your problem.

This screenshot shows both issues:
![Screenshot from 2023-05-07 09-15-18](https://user-images.githubusercontent.com/1524089/236689686-2b3f7265-4764-43f8-9301-922fff1249c8.png)

The thicker top bar is affected by the Shell setting in gnome tweaks, and the Java window artifact is affected by the Legacy Applications setting. (The Java apps that show the artifact are the JetBrains IDE's)

**Comment by r7l** [comment]
I have the same issue starting with Gnome 44.x and it's not related to Java or anything else. I have this issue on Chrome, Firefox, GTK and QT based applications and pretty much everything else. It's reproduceable by going back and forth between Gnome 43 (ok) and 44 (broken).

- Distribution and version: Gentoo without Wayland
- Versions for the affected: gnome-base/gnome-shell-44.1
- Installation method: Gentoo Portage
- Arc-theme version: x11-themes/arc-theme-20221218

![gnome](https://user-images.githubusercontent.com/30982145/236696622-91c5d2a6-f492-4446-8b47-6bde77d8205d.png)

From what i've noted, the issue can be removed temporarily by switching fullscreen window and back. It's also not just black and white like shown in the screenshots here but instead it's might even show remains of any window and content shown above the window in question after the overlapping window has been moved or closed.

**Comment by jnsh** [comment]
Thanks for the report. I noticed this myself after the GNOME 44 update rolled to Arch Linux repositories. My best guess right now is that this is related to mutter switching to GTK4 instead of GTK3, and therefore now using GTK4 theme for the decorations.

I'll try to have some time to update the theme for the latest GNOME release soon, and hopefully I'll figure solution for this issue as well.

**Comment by jnsh** [comment]
This seems to be fixed in gnome-shell/mutter 44.2

**Comment by r7l** [comment]
I've not updated for now since it was still working ok. I've just updated to 44.2 and the issue is still there.

**Comment by jnsh** [comment]
> I've not updated for now since it was still working ok but i've just updated to 44.2 and the issue is still there.

Have you restarted your shell (including GDM) since the upgrade? I cannot reproduce this any more after updating to 44.2 on Arch on either X11 or Wayland.

**Comment by Bosma** [comment]
To clarify: my original post had 2 issues. Last I checked, the thick border still existed, but the weird window border glitching was fixed.

**Comment by jnsh** [comment]
> To clarify: my original post had 2 issues. Last I checked, the thick border still existed, but the weird window border glitching was fixed.

My apologies, I only noted the window border glitch, which was fixed in 44.2.

The thick top bar border still remains, but it should get fixed by upgrading the Arc shell theme CSS for GNOME 44, which I still haven't got into unfortunately.

**Comment by r7l** [comment]
I still have these glitches and i've tried to update and downgrade back and forth but it won't change. I've also rebooted my machine a number of times. It also didn't help. I've even tested "[Arc-Darkest-Desktop](https://github.com/rtlewis1/GTK/tree/Arc-Darkest-Desktop)" but it gives me the same issues.

Had to switch back to Adwaita for the time being. Wow! Forgot how ugly it is. And they are not even able to keep the buttons the same on all applications. What a mess. But still forcing people to this crap. But well, those glitches are even worse to look at. Especially when not using fullscreen since i have a very large monitor.

Thanks allot for all the time and effort you've spend into this theme. I really loved using it but those glitches are annoying. I am not even blaming you. It's the Gnome devs always working hard on breaking things on every new release.

**Comment by jnsh** [comment]
> I still have these glitches and i've tried to update and downgrade back and forth but it won't change (with any 44.x version). I've also rebooted my machine a number of times. It also didn't help. I've even tested [Arc-Darkest-Desktop](https://github.com/rtlewis1/GTK/tree/Arc-Darkest-Desktop) but it gives me the same issues.

Since the glitch isn't present on Adwaita, there is most likely some way to make it disappear in Arc as well. However finding what small thing happens to result in this is pretty much guesswork, but I'll see if I can take a look at some point.

> Had to switch back to Adwaita for the time being. Wow! Forgot how ugly it is. And they are not even able to keep the buttons the same on all applications. What a mess. But still forcing people to this crap. But well, those glitches are even worse to look at. Especially when not using fullscreen since i have a very large monitor.
> 
> Thanks allot for all the time and effort you've spend into this theme. I really loved using it but those glitches are annoying. I am not even blaming you. It's the Gnome devs always working hard on breaking things on every new release.

With all due respect, please remain respectful towards open source projects and developers who are working hard ti provide free software for you and everyone else, even if something about it isn't to your preference or there happens to be some issues.

Adwaita is not by any means a bad theme, even if it's not your (and my) cup of tea. No developer is breaking anything on purpose, and you can't really blame gnome devs for missing an issue that is only apparent on some certain third party theme. This is sort of one of the reasons they want to discourage people from using custom themes anyway..

**Comment by r7l** [comment]
@jnsh Have you seen this? https://gitlab.gnome.org/GNOME/mutter/-/issues/2725 

Sorry for my rant recently. I am just unhappy with Gnome constantly causing issue on each update. This is by far the worst one. Since i am still unhappy with Adwaita, i've tried a number of other themes i've found. Those glitches are on every of them to a different extend. Some only have a couple tiny black spots floating around somewhere and others have even worse issues then Arc.

**Comment by r7l** [comment]
Found a fix for issue with those glitches. Updating to GTK 4.10.4 does the trick.

Related PR for the fix: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5857

**Comment by jnsh** [comment]
> Found a fix for issue with those glitches. Updating to GTK 4.10.4 does the trick.

Makes sense, since GTK is actually drawing the decorations. Thanks for figuring this out :)

Closing this again. As mentioned, the top panel border should be a matter of updating the theme CSS, and separate from the window decoration glitches. I'll be using #212 for tracking the CSS regressions.
